name: Docker Build
description: Build a Docker image with configurable Dockerfile, image name, and tag
inputs:
  path_dockerfile:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Docker image name"
    required: true
  tag_name:
    description: "Docker image tag"
    required: false

runs:
  using: composite
  steps:
    - name: Build Docker image
      shell: bash
      run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          export TAG=$(date +%s)
        else
          export TAG="${{ inputs.tag_name }}"
        fi

        docker build . \
          --file "${{ inputs.path_dockerfile }}" \
          --tag "${{ inputs.image_name }}:${TAG}"
